envs:
  default:
    widgets:
      gToolButton:
        defaultIconSize: 16

      gMediumToolButton:
        defaultIconSize: 24
      gSmallToolButton:
        defaultIconSize: 16
      gLargeToolButton:
        defaultIconSize: 32

      #
      # Configuration for the dock with pyramids and status
      #
      dockCraftingZone:
        toolbarPyramids:
          visible: True
          iconSize: 32

          # Unused for now
          maxActionsPerRow: 12

        toolbarAppStatus:
          visible: True
          iconSize: 24
