envs:
  default:
    # Theme used
    theme: 'breeze-dark'

    objectOpener:
      mimeTypes:
        default:
          slowObjectTimer: 6

    styles:
      # galacteek Qt style
      galacteek:
        styleType: 'desktopGeneric'

        desktopGeneric:
          # Pixel metrics
          metrics:
            toolBarIconSize: 32
            toolBarItemSpacing: 2
            toolBarItemMargin: 0
            toolBarSeparatorExtent: 2

            buttonDefaultIconSize: 16

            tabBarIconSize: 16
            textCursorWidth: 12

            scrollBarExtent: 32

    notifications:
      tagSearchSuccess:
        sound: apert

      luckySearch:
        sound: space2

      pyramidAdded:
        sound: space
      pyramidConfigured:
        sound: space
      pyramidCreated:
        sound: space

      pyramidInputNew:
        sound: apert
      pyramidOutputNew:
        sound: approved-mission

      workspaceSwitched:
        control:
          sound: apert.wav
